<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="stpl" nsURI="platform:/tdt4250.adsoftdesign/model/stpl.ecore"
    nsPrefix="stpl">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credits" eType="#//Credit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="course" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Credit">
    <eLiterals name="FIVEPOINTS" literal="5"/>
    <eLiterals name="SEVENHALFPOINTS" value="1" literal="7.5"/>
    <eLiterals name="TENPOINTS" value="2" literal="10"/>
    <eLiterals name="FIFTEENPOINTS" value="3" literal="15"/>
    <eLiterals name="TWENTYPOINTS" value="4" literal="20"/>
    <eLiterals name="THIRTYPOINTS" value="5" literal="30"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="minimumOneCourse"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="teachingSemester" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="electives" upperBound="-1"
        eType="#//Course"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatories" upperBound="-1"
        eType="#//Course"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="studySpecialization" eType="#//StartOfStudy"
        eOpposite="#//StartOfStudy/semesters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartOfStudy">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="minSemesters"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="minSemesters" value="self.semesters->size() >= 4"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" upperBound="-1"
        eType="#//Semester" containment="true" eOpposite="#//Semester/studySpecialization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="program" eType="#//Specialization"
        eOpposite="#//Specialization/studySpecializations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialization">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="studySpecializations" eType="#//StartOfStudy"
        containment="true" eOpposite="#//StartOfStudy/program"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subspecialization" upperBound="-1"
        eType="#//Specialization"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StudyPlan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="directions" upperBound="-1"
        eType="#//Specialization" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
